# Cloud Build configuration for Volunteer Portal.
# See builds here:
# https://console.cloud.google.com/cloud-build/builds?query=trigger_id%3D%22470d9eab-c7ec-4b6c-bfa6-313214e15107%22&project=humanity-forward
steps:
  - name: node
    entrypoint: npm
    args:
    - ci
  - name: node
    entrypoint: npm
    args:
    - run
    - build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
    - '-c'
    - |
      if [ "${BRANCH_NAME}" == "master" ]; then
        gcloud app deploy --quiet
      elif [ "${BRANCH_NAME}" == "staging" ]; then
        gcloud app deploy --quiet --version staging --no-promote
      elif [ "${BRANCH_NAME}" == "testing" ]; then
        gcloud app deploy --quiet --version testing --no-promote
      fi
    id: Deploy
tags:
  - gcp-cloud-build-deploy-appengine

