version: "3.7"

services:
  # db:
  #   build:
  #     context: ./
  #     dockerfile: ./db/Dockerfile
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   ports:
  #   - 8082:5432

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
    - "ENV=development"
    ports:
    - 8080:8080
    - 5432:8082

  # adminer:
  #   image: adminer
  #   ports:
  #   - 8080:8080
  #
  # client:
  #   image: node
  #   environment:
  #   - "DANGEROUSLY_DISABLE_HOST_CHECK=true"
  #   volumes:
  #   - ./client:/home/node/app
  #   working_dir: /home/node/app
  #   command: ["npm", "run", "client"]
  #
  #

  #
  # proxy:
  #   image: nginx
  #   volumes:
  #   - ./nginx:/etc/nginx/conf.d
  #   ports:
  #   - 55433:80
