version: "3.7"

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  api:
    build: ./api
    command: uvicorn --host 0.0.0.0 api:app --app-dir . --port 8081
    depends_on:
    - db
    ports:
    - 8081:8081
    volumes:
    - ./api:/api

  client:
    build: ./client
    command: npm run start
    environment:
    - "DANGEROUSLY_DISABLE_HOST_CHECK=true"
    ports:
    - 8080:8080
    volumes:
    - ./client:/client
    - client_node_modules:/srv/client/node_modules

  # adminer:
  #   image: adminer
  #  ports:
  #  - 8080:8080


  # proxy:
  #   image: nginx
  #   depends_on:
  #   - api
  #   - client
  #   volumes:
  #   - ./nginx:/etc/nginx/conf.d
  #   ports:
  #   - 55433:80


volumes:
  client_node_modules:
