version: "3.7"

services:
  api:
    build: ./api
    command: uvicorn --host 0.0.0.0 api:app --app-dir . --port 8081 --reload
    depends_on:
      db:
        condition: service_healthy
    ports:
    - 8081:8081
    volumes:
    - ./api:/api

  client:
    build:
      context: ./client
      network: host
    command: npm run client

    depends_on:
    - api
    environment:
    - "DANGEROUSLY_DISABLE_HOST_CHECK=true"
    ports:
    - 8080:8080
    volumes:
    - ./client:/client
    - /client/node_modules

  db:
    build: ./db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
    - 8082:5432 # For local connection via a Postgres client
    volumes:
    - ./db/data/dev:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 1s
      timeout: 10s
      retries: 10

  # Proxy allows the client app to access the API on the same host
  # This avoids cross-domain issues.
  # This is the main entrypoint to the application.
  proxy:
    image: nginx
    depends_on:
    - api
    - client
    volumes:
    - ./nginx:/etc/nginx/conf.d
    ports:
    - 8000:80
    - 80:80
