# Dev config
# Use "docker-comppose -f docker-compose.yml -f docker-compose.test.yml up" to extend and override
# the base configs in docker-compose.yml with this config.
services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
    - 8082:5432 # For local connection via a Postgres client
    volumes:
    - ./db/data/test:/docker-entrypoint-initdb.d

  api:
    environment:
      ENV: test
      GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json
