# Dev config
# Calling "docker-compose up" uses the configuration set in docker-compose.yml then
# extends and overwrites those values with the configuration here
services:
  api:
    environment:
      ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json
