version: "3.7"

services:
  db:
    build: .
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
    - data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  adminer:
    image: adminer
    ports:
    - 8080:8080

volumes:
  data:
