runtime: python38
entrypoint: gunicorn api:app -w 4 -k uvicorn.workers.UvicornWorker
service: volunteer-portal-api
instance_class: F4  
vpc_access_connector:
  name: projects/humanity-forward/locations/us-central1/connectors/volunteer-portal-12-20
