production_server_defaults: &production_server_defaults
    adapter: mysql
    generator: secret_generator
    host: 35.188.204.248
    database: airtable_database
    user: no_pii
    password: humanity-forward_hf-db1-mysql_no_pii

test:
    database:
        generator: db_url_generator
        adapter: postgresql
        host: db
        database: hf_volunteer_portal_test
        user: admin
        password: password
development:
    database:
        generator: db_url_generator
        adapter: postgresql
        host: db
        database: hf_volunteer_portal_development
        user: admin
        password: password
staging:
    database:
        <<: *production_server_defaults
production:
    database:
        <<: *production_server_defaults
