# Aliases for common sections of configuration across environments

production_db_defaults: &production_db_defaults
  database:
    adapter: mysql
    generator: secret_generator
    host:
    database:
      adapter: postgresql
      generator: secret_generator
      host: 10.17.1.3
      database: hf_volunteer_portal
      user: admin
      password: humanity-forward_hf-portal_psql-db_admin

development_routes_defaults: &development_routes_defaults
  client: 'http://localhost:8000'

auth_defaults: &auth_defaults
  jwt:
    secret: portal_auth_jwt_secret
  google:
    client_id: portal_auth_google_client_id
    client_secret: portal_auth_google_client_secret
  github:
    client_id: portal_auth_github_client_id
    client_secret: portal_auth_github_client_secret

notification_defaults: &notification_defaults
  email_default_from_address: tripp@movehumanityforward.com
  sendgrid_api_key: portal_notifications_sendgrid_test_api_key
  sms_default_from_number: '+18053348626'
  twilio_sid: portal_notifications_twilio_sid
  twilio_auth_token: portal_notifications_twilio_auth_token
  slack_bot_auth_token: portal_notifications_slack_bot_auth_token

# Specific configurations for each environment

test:
  routes:
    <<: *development_routes_defaults
  databases:
    database:
      generator: db_url_generator
      adapter: postgresql
      host: db
      database: hf_volunteer_portal_test
      user: admin
      password: password
  auth:
    <<: *auth_defaults
  notifications:
    <<: *notification_defaults
development:
  routes:
    <<: *development_routes_defaults
  databases:
    database:
      generator: db_url_generator
      adapter: postgresql
      host: db
      database: hf_volunteer_portal_development
      user: admin
      password: password
  auth:
    # import_auth_credentials_from_secret_store: false
    <<: *auth_defaults
  notifications:
    <<: *notification_defaults
staging:
  # TODO verify that this is fine as long as the traffic is all proxies within a single machine.
  routes:
    <<: *development_routes_defaults
  databases:
    <<: *production_db_defaults
  auth:
    <<: *auth_defaults
  # TODO update to proper staging config
  notifications:
    <<: *notification_defaults
production:
  databases:
    <<: *production_db_defaults
  auth:
    <<: *auth_defaults
  # TODO add production notification configs
