
name: Staging Client Deployment
on:
  push:
    branches: [ master ]
    paths: [ 'client/**' ]

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GAE_SERVICE_ACCOUNT }}
        deliverables: client/prod-client.yaml
