name: Python CI

on:
  push:
    branches: [ master, staging, python-ci ]
  pull_request:
    branches: [ master, staging ]
defaults:
  run:
    shell: bash
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Create/Activate conda environment and Lint
      run: |
        conda env create
        source ~/miniconda3/etc/profile.d/conda.sh
        conda activate volunteer-portal
        mypy ./api
