name: Python CI

on:
  push:
    branches: [ production, develop ]
  pull_request:
    branches: [ production, develop ]

defaults:
  run:
    shell: bash
    working-directory: api

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup
      run:
        pip install -r requirements.txt
    - name: Lint
      run:
        mypy .
