
name: Deployment
on:
  push:
    branches: [ staging, appengine_cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GAE_SERVICE_ACCOUNT }}
        deliverables: ./api/staging-app.yaml

