
name: Staging API Deployment
on:
  push:
    branches: [ staging ]
    paths: [ 'api/**' ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GAE_SERVICE_ACCOUNT }}
        deliverables: ./api/staging-app.yaml
