name: Test CI

on:
  push:
    branches: [ production, develop ]
  pull_request:
    branches: [ production, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Python Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm api python -m pytest tests/
      - name: JavaScript Tests
        run: docker-compose run --rm client npm test -- --passWithNoTests --ci --watchAll=false
